name: Elizabeth Yankovsky
author: Herring Cove
root: /herring-cove
description: Ph.D. Candidate in Atmospheric and Oceanic     Sciences, Princeton University
github: http://www.github.com/ElizabethYankovsky
email: eyankovsky@gmail.com

highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
