name: Elizabeth Yankovsky
author: Elizabeth Yankovsky
github: http://www.github.com/ElizabethYankovsky
email: eyankovsky@gmail.com

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
